version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    environment:
     - 'MYSQL_DATABASE=db_ms-race'
     - 'MYSQL_ROOT_PASSWORD=root'
     - 'MYSQL_ALLOW_EMPTY_PASSWORD=yes'
    ports:
      - '3306:3306'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=root'
      - 'RABBITMQ_DEFAULT_USER=root'
    ports:
      - '5672:5672'
  race-service:
    build:
      context: ./ms-race
      dockerfile: Dockerfile
    ports:
     - "8082:8082"
    depends_on:
      - mysql
      - rabbitmq
    command: ["sh", "-c", "sleep 1 && java -jar ms-race-0.0.1-SNAPSHOT.jar"]

  db:
    image: 'postgres:15.3'
    environment:
      - POSTGRES_DB=db_ms-cars
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - "5432:5432"
  car-service:
    build:
      context: ./ms-cars
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    command: ["sh", "-c", "sleep 60 && java -jar ms-cars-0.0.1-SNAPSHOT.jar"]

