version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=db_ms-race'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=yes'
    ports:
      - '3306:3306'

  rabbitmq:
    image: 'rabbitmq:latest'
    ports:
      - '5672:5672'
      - '15672:15672'

  ms-race:
    build:
      context: ./ms-race
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - rabbitmq
      - ms-cars
    command: [ "sh", "-c", "sleep 480 && java -jar ms-race-0.0.1-SNAPSHOT.jar" ]

  db:
    image: 'postgres:15.3'
    environment:
      - POSTGRES_DB=db_ms-cars
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - "5432:5432"

  ms-cars:
    build:
      context: ./ms-cars
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    command: [ "sh", "-c", "sleep 600 && java -jar ms-cars-0.0.1-SNAPSHOT.jar" ]

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    command: mongod --auth


  ms-history:
    build:
      context: ./ms-history
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - db
      - rabbitmq
      - ms-race
    command: [ "sh", "-c", "sleep 660 && java -jar ms-history-0.0.1-SNAPSHOT.jar" ]
