version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    environment:
     - 'MYSQL_DATABASE=db_ms-race'
     - 'MYSQL_ROOT_PASSWORD=root'
     - 'MYSQL_ALLOW_EMPTY_PASSWORD=yes'
    ports:
      - '3306:3306'
    networks:
      - default
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=root'
      - 'RABBITMQ_DEFAULT_USER=root'
    ports:
      - '5672:5672'
    networks:
      - default
  race-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8082:8082"
    networks:
     - default
     - ms-cars
    depends_on:
      - mysql
      - rabbitmq
    command: ["sh", "-c", "sleep 1 && java -jar ms-race-0.0.1-SNAPSHOT.jar"]

networks:
  default:
    driver: bridge
  ms-cars:
    external: true