version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    environment:
     - 'MYSQL_DATABASE=db_ms-race'
     - 'MYSQL_ROOT_PASSWORD=root'
     - 'MYSQL_ALLOW_EMPTY_PASSWORD=yes'
    ports:
      - '3306:3306'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=root'
      - 'RABBITMQ_DEFAULT_USER=root'
    ports:
      - '15672:15672'
  race-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8082:8082"
    depends_on:
      - mysql
      - rabbitmq
    command: ["sh", "-c", "sleep 60 && java -jar ms-race-0.0.1-SNAPSHOT.jar"]
