version: '3'
services:
  db:
    image: 'postgres:15.3'
    environment:
      - POSTGRES_DB=db_ms-cars
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - "5432:5432"
    networks:
      - OpenFeign
  car-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - OpenFeign
    depends_on:
      - db
    command: ["sh", "-c", "sleep 60 && java -jar ms-cars-0.0.1-SNAPSHOT.jar"]
networks:
  OpenFeign: